DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS matches_updates;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS items_images;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS reports;