import Constants from 'expo-constants';
const extra = Constants.expoConfig?.extra;

export const EXPO_PUBLIC_ENV_ID = extra?.EXPO_PUBLIC_ENV_ID;
export const EXPO_PUBLIC_SERVER_HOST = extra?.EXPO_PUBLIC_SERVER_HOST;
export const EXPO_PUBLIC_PORT = extra?.EXPO_PUBLIC_PORT;
export const EXPO_PUBLIC_JWT_SECRET = extra?.EXPO_PUBLIC_JWT_SECRET;
export const EXPO_PUBLIC_SERVER_PORT = extra?.EXPO_PUBLIC_SERVER_PORT;
export const EXPO_PUBLIC_POSTGRESQL_CONTAINER_NAME = extra?.EXPO_PUBLIC_POSTGRESQL_CONTAINER_NAME;
export const EXPO_PUBLIC_DB_CONNECTION_URL = extra?.EXPO_PUBLIC_DB_CONNECTION_URL;
export const EXPO_PUBLIC_DB_USER = extra?.EXPO_PUBLIC_DB_USER;
export const EXPO_PUBLIC_DB_PASSWORD = extra?.EXPO_PUBLIC_DB_PASSWORD;
export const EXPO_PUBLIC_DB_NAME = extra?.EXPO_PUBLIC_DB_NAME;
export const EXPO_PUBLIC_DB_HOST = extra?.EXPO_PUBLIC_DB_HOST;
export const EXPO_PUBLIC_DB_PORT = extra?.EXPO_PUBLIC_DB_PORT;
export const EXPO_PUBLIC_SQL_FILE = extra?.EXPO_PUBLIC_SQL_FILE;
export const EXPO_PUBLIC_STORAGE_APP_KEY_ID = extra?.EXPO_PUBLIC_STORAGE_APP_KEY_ID;
export const EXPO_PUBLIC_STORAGE_APP_KEY = extra?.EXPO_PUBLIC_STORAGE_APP_KEY;
export const EXPO_PUBLIC_STORAGE_FILES_BASE_URL = extra?.EXPO_PUBLIC_STORAGE_FILES_BASE_URL;
export const EXPO_PUBLIC_BUCKET_SUFFIX = extra?.EXPO_PUBLIC_BUCKET_SUFFIX;
export const EXPO_PUBLIC_EMAIL_ADDRESS = extra?.EXPO_PUBLIC_EMAIL_ADDRESS;
export const EXPO_PUBLIC_EMAIL_PASSWORD = extra?.EXPO_PUBLIC_EMAIL_PASSWORD;
// only for local
export const EXPO_PUBLIC_SERVER_HOST_IP = extra?.EXPO_PUBLIC_SERVER_HOST_IP;
